nuls2:
  chain_id: 1
  enabled: True
  packing_node: False
  private_key: YOUR_PRIVATE_KEY_HERE
  sync_address: NULSd6HgUkssMi6oSjwEn3puNSijLKnyiRV7H
  api_url: https://apiserver.nuls.io/
  explorer_url: https://nuls.world/
  token_contract: NULSd6Hh1FjbnAktH1FFvFnTzfgFnZtgAhYut

ethereum:
  enabled: True
  api_url: http://10.111.100.214:8545  # Remplacer par l'adresse rinkeby depuis infura
  chain_id: 4
  packing_node: False
  private_key: YOUR_PRIVATE_KEY_HERE
  sync_contract: "0x6aDF64fC26D495445A3CAB545aC808d66932aC15"
  start_height: 5042280
  token_contract: "0xc0134b5b924c2fca106efb33c45446c466fbe03e"

binancechain:
  enabled: True
  packing_node: False
  private_key: YOUR_PRIVATE_KEY_HERE
  sync_address: bnb1r3rf8cj9t2w6v0za3ufyp03as3nv6rjxteku6g
  start_time: "2019-05-22T00:00:00Z"

mongodb:
  uri: "mongodb://127.0.0.1"
  database: alephtest

storage:
  store_files: true
  engine: mongodb

ipfs:
  host: 127.0.0.1
  port: 5001
  gateway_port: 8080

aleph:
  queue_topic: ALEPH-TEST

p2p:
  host: 0.0.0.0
  port: 4025  # faire une ouverture de ports
  http_port: 4024  # faire une ouverture de ports
  key: null
  reconnect_delay: 60
